FROM node:carbon-alpine

ENV NODE_ENV=development

RUN apk update \
  && apk upgrade \
  && apk add --no-cache \
    git \
    make \
    gcc \
    g++ \
    python

RUN npm config set unsafe-perm true

WORKDIR /bitcore

COPY . .

RUN npm install

RUN apk del \
  git \
  make \
  gcc \
  g++ \
  python \
  && rm /var/cache/apk/*
